name = "pipecommerce-admin"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# ─── Bindings (commented — uncomment when ready) ─────────────────────────────

# [[hyperdrive]]
# binding = "HYPERDRIVE"
# id = "TODO"
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "c69bebaa86c64434b14d49c393dae1f1"

[[kv_namespaces]]
binding = "SHOP_KV"
id = "edcf63b86b7e4a2088d779e1f2eb38cb"

[[r2_buckets]]
binding = "pipecommerce"
bucket_name = "pipecommerce"

# [[queues.producers]]
# binding = "EMAIL_QUEUE"
# queue = "email"

[vars]
PLATFORM_DOMAIN = "pipecommerce.app"
