-- Phase 2k — Row Level Security (DEPRECATED 2026-05-11)
--
-- เดิมเปิด RLS ทุก table ของ Supabase + ใช้ auth.uid() เป็น helper
-- แต่ปี 2026-05 เรา migrate ออก Cloudflare Workers + Supabase → Railway PG
-- (ดู ADR-020 / docs/RAILWAY.md)
--
-- Railway PG ไม่มี schema `auth` และไม่มี roles `anon`/`authenticated`
-- → authorization ย้ายไป application layer (Server Actions ตรวจ shop_members
--   membership ก่อนทุก mutation ผ่าน lib/shop.ts:requireShop)
--
-- ไฟล์นี้คงไว้เพื่อรักษา migration history; runtime ไม่ทำอะไร
SELECT 1;
